version: '3'

services:
  my_postgres:
    container_name: my_postgres
    image: postgres:12-alpine
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "Abcd1234"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data # persist data even if container shuts down
    ports:
      - "5432:5432"
    networks:
      - postgres-net
    
  my_pgadmin4:
    container_name: my_pgadmin4
    image: dpage/pgadmin4
    restart: "always"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "hihihi@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "Abcd1234"
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - postgres-net

#
# [ networks definition ]
#
networks:
  postgres-net:
    external: true

#
# [ volumes definition ]
# creates Docker volumes which can be mounted by other containers too e.g. for backup
#
volumes:
  postgres-data:
    external: true
  pgadmin4-data:
    external: true
    